In [5]:
import torch
import torch.nn as nn

In [6]:
layer = nn.Linear(40, 10)
layer.weight.data *= 6 ** 0.5
torch.zero_(layer.bias.data)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
nn.init.kaiming_uniform_(layer.weight)
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

In [8]:
def use_he_init(module):
    if isinstance(module, nn.Linear):
        nn.init.kaiming_uniform_(module.weight)
        nn.init.zeros_(module.bias)

model = nn.Sequential(nn.Linear(50, 40), nn.ReLU(), nn.Linear(40, 1), nn.ReLU())
model.apply(use_he_init)

Sequential(
  (0): Linear(in_features=50, out_features=40, bias=True)
  (1): ReLU()
  (2): Linear(in_features=40, out_features=1, bias=True)
  (3): ReLU()
)

In [9]:
alpha = 0.2
model = nn.Sequential(nn.Linear(50, 40), nn.LeakyReLU(negative_slope=alpha))
nn.init.kaiming_uniform_(model[0].weight, alpha, nonlinearity="leaky_relu")

Parameter containing:
tensor([[-0.3012,  0.0605,  0.2078,  ...,  0.2911, -0.0570, -0.0262],
        [-0.1612, -0.1670, -0.1684,  ..., -0.1771,  0.2858,  0.3227],
        [ 0.2425,  0.2033, -0.0897,  ..., -0.1549,  0.0624, -0.2092],
        ...,
        [-0.1695,  0.0889, -0.3000,  ..., -0.2374, -0.3099, -0.2197],
        [-0.1623, -0.2578,  0.1144,  ...,  0.2313,  0.2752,  0.2382],
        [-0.0549, -0.0615,  0.0178,  ...,  0.2292, -0.0884, -0.0142]],
       requires_grad=True)