In [111]:
import torch
from torch.nn import grad

In [112]:
X = torch.tensor([
    [1.0, 4.0, 7.0],
    [2.0, 3.0, 6.0]
])
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [113]:
X.shape

torch.Size([2, 3])

In [114]:
X.dtype

torch.float32

In [115]:
X[0, 1]

tensor(4.)

In [116]:
X[[0, 1]]

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [117]:
X[:, 1]

tensor([4., 3.])

In [118]:
10 * (X + 1)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [119]:
X.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [120]:
X.mean()

tensor(3.8333)

In [121]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [122]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

In [123]:
import numpy as np

X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [124]:
torch.tensor(np.array([
    [1, 4, 7],
    [2, 3, 6]
]), dtype=torch.float64)

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [125]:
torch.FloatTensor(np.array([[1., 4., 7.], [2., 3., 6]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [126]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [127]:
X.relu_()

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [128]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [129]:
M = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=torch.float32)
M = M.to(device)

In [130]:
M.device

device(type='cuda', index=0)

In [131]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device=device)

In [132]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

In [133]:
M = torch.rand((1000, 1000))
%timeit M @ M.T

3.65 ms ± 4.48 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [134]:
M = torch.rand((1000, 1000), device=device)
%timeit M @ M.T

369 μs ± 8.44 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [135]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
f

tensor(25., grad_fn=<PowBackward0>)

In [136]:
f.backward()
x.grad

tensor(10.)

In [137]:
t = 5
lr = 0.001
epochs = 100

x = torch.tensor(10.0)

w = torch.tensor(10.0, requires_grad=True)


for i in range(epochs):
    f = x * w
    L = (f - t) ** 2

    L.backward()

    # with torch.no_grad():
    #     w -= lr * w.grad
    w_detached = w.detach()
    w_detached -= lr * w.grad

    w.grad.zero_()

    print("w: ", w)

print(w.grad)

w:  tensor(8.1000, requires_grad=True)
w:  tensor(6.5800, requires_grad=True)
w:  tensor(5.3640, requires_grad=True)
w:  tensor(4.3912, requires_grad=True)
w:  tensor(3.6130, requires_grad=True)
w:  tensor(2.9904, requires_grad=True)
w:  tensor(2.4923, requires_grad=True)
w:  tensor(2.0938, requires_grad=True)
w:  tensor(1.7751, requires_grad=True)
w:  tensor(1.5201, requires_grad=True)
w:  tensor(1.3160, requires_grad=True)
w:  tensor(1.1528, requires_grad=True)
w:  tensor(1.0223, requires_grad=True)
w:  tensor(0.9178, requires_grad=True)
w:  tensor(0.8343, requires_grad=True)
w:  tensor(0.7674, requires_grad=True)
w:  tensor(0.7139, requires_grad=True)
w:  tensor(0.6711, requires_grad=True)
w:  tensor(0.6369, requires_grad=True)
w:  tensor(0.6095, requires_grad=True)
w:  tensor(0.5876, requires_grad=True)
w:  tensor(0.5701, requires_grad=True)
w:  tensor(0.5561, requires_grad=True)
w:  tensor(0.5449, requires_grad=True)
w:  tensor(0.5359, requires_grad=True)
w:  tensor(0.5287, requir

In [138]:
learning_rate = 0.1
x = torch.tensor(5.0, requires_grad=True)
for i in range(100):
    f = x ** 2
    f.backward()
    with torch.no_grad():
        x -= learning_rate * x.grad
    x.grad.zero_()
    print(x)

tensor(4., requires_grad=True)
tensor(3.2000, requires_grad=True)
tensor(2.5600, requires_grad=True)
tensor(2.0480, requires_grad=True)
tensor(1.6384, requires_grad=True)
tensor(1.3107, requires_grad=True)
tensor(1.0486, requires_grad=True)
tensor(0.8389, requires_grad=True)
tensor(0.6711, requires_grad=True)
tensor(0.5369, requires_grad=True)
tensor(0.4295, requires_grad=True)
tensor(0.3436, requires_grad=True)
tensor(0.2749, requires_grad=True)
tensor(0.2199, requires_grad=True)
tensor(0.1759, requires_grad=True)
tensor(0.1407, requires_grad=True)
tensor(0.1126, requires_grad=True)
tensor(0.0901, requires_grad=True)
tensor(0.0721, requires_grad=True)
tensor(0.0576, requires_grad=True)
tensor(0.0461, requires_grad=True)
tensor(0.0369, requires_grad=True)
tensor(0.0295, requires_grad=True)
tensor(0.0236, requires_grad=True)
tensor(0.0189, requires_grad=True)
tensor(0.0151, requires_grad=True)
tensor(0.0121, requires_grad=True)
tensor(0.0097, requires_grad=True)
tensor(0.0077, requires_

In [139]:
t = torch.tensor(2.0, requires_grad=True)
z = t.exp()  # this is an intermediate result
z += 1  # this is an in-place operation
z.backward()  #  RuntimeError!

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor []], which is output 0 of ExpBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

In [140]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

housing = fetch_california_housing()

X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target, random_state=42
)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42
)

In [141]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
X_train = std_scaler.fit_transform(X_train)
X_valid = std_scaler.transform(X_valid)
X_test = std_scaler.transform(X_test)

X_train = torch.FloatTensor(X_train)
X_valid = torch.FloatTensor(X_valid)
X_test = torch.FloatTensor(X_test)

In [142]:
X_train.shape

torch.Size([11610, 8])

In [143]:
y_train = torch.FloatTensor(y_train).reshape(-1, 1)
y_valid = torch.FloatTensor(y_valid).reshape(-1, 1)
y_test = torch.FloatTensor(y_test).reshape(-1, 1)

In [144]:
torch.manual_seed(42)
n_features = X_train.shape[1]
w = torch.randn((n_features, 1), requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [169]:
learning_rate = 0.4
n_epochs = 20
for _ in range(n_epochs):
    y_pred = X_train @ w + b
    loss = ((y_pred - y_train) ** 2).mean()
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(f"Epoch: {_}, loss: {loss}")

Epoch: 0, loss: 0.5246028900146484
Epoch: 1, loss: 0.5246028900146484
Epoch: 2, loss: 0.5246028304100037
Epoch: 3, loss: 0.5246028900146484
Epoch: 4, loss: 0.5246028900146484
Epoch: 5, loss: 0.5246028304100037
Epoch: 6, loss: 0.5246028304100037
Epoch: 7, loss: 0.5246028304100037
Epoch: 8, loss: 0.5246028304100037
Epoch: 9, loss: 0.5246028304100037
Epoch: 10, loss: 0.5246028304100037
Epoch: 11, loss: 0.5246028900146484
Epoch: 12, loss: 0.5246028900146484
Epoch: 13, loss: 0.5246028900146484
Epoch: 14, loss: 0.5246028900146484
Epoch: 15, loss: 0.5246028900146484
Epoch: 16, loss: 0.5246028900146484
Epoch: 17, loss: 0.5246028900146484
Epoch: 18, loss: 0.5246028900146484
Epoch: 19, loss: 0.5246028900146484


In [174]:
from sklearn.metrics import mean_absolute_error

X_new = X_test
with torch.no_grad():
    y_pred = X_new @ w + b

mae = mean_absolute_error(y_pred, y_test)
mae

0.5254672765731812