In [1]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms.v2 as T
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from torch.utils.data import TensorDataset, DataLoader
import torchmetrics

In [2]:
X = torch.tensor([
    [1.0, 4.0, 7.0],
    [2.0, 3.0, 6.0]
])
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [3]:
X.shape

torch.Size([2, 3])

In [4]:
X.dtype

torch.float32

In [5]:
X[0, 1]

tensor(4.)

In [6]:
X[[0, 1]]

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [7]:
X[:, 1]

tensor([4., 3.])

In [8]:
10 * (X + 1)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [9]:
X.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [10]:
X.mean()

tensor(3.8333)

In [11]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [12]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

In [13]:
import numpy as np

X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [14]:
torch.tensor(np.array([
    [1, 4, 7],
    [2, 3, 6]
]), dtype=torch.float64)

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [15]:
torch.FloatTensor(np.array([[1., 4., 7.], [2., 3., 6]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [16]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [17]:
X.relu_()

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [18]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [19]:
M = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=torch.float32)
M = M.to(device)

In [20]:
M.device

device(type='cuda', index=0)

In [21]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device=device)

In [22]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

In [23]:
M = torch.rand((1000, 1000))
%timeit M @ M.T

4.35 ms ± 220 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
M = torch.rand((1000, 1000), device=device)
%timeit M @ M.T

373 μs ± 2.99 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [25]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
f

tensor(25., grad_fn=<PowBackward0>)

In [26]:
f.backward()
x.grad

tensor(10.)

In [27]:
t = 5
lr = 0.001
epochs = 100

x = torch.tensor(10.0)

w = torch.tensor(10.0, requires_grad=True)


for i in range(epochs):
    f = x * w
    L = (f - t) ** 2

    L.backward()

    # with torch.no_grad():
    #     w -= lr * w.grad
    w_detached = w.detach()
    w_detached -= lr * w.grad

    w.grad.zero_()

    print("w: ", w)

print(w.grad)

w:  tensor(8.1000, requires_grad=True)
w:  tensor(6.5800, requires_grad=True)
w:  tensor(5.3640, requires_grad=True)
w:  tensor(4.3912, requires_grad=True)
w:  tensor(3.6130, requires_grad=True)
w:  tensor(2.9904, requires_grad=True)
w:  tensor(2.4923, requires_grad=True)
w:  tensor(2.0938, requires_grad=True)
w:  tensor(1.7751, requires_grad=True)
w:  tensor(1.5201, requires_grad=True)
w:  tensor(1.3160, requires_grad=True)
w:  tensor(1.1528, requires_grad=True)
w:  tensor(1.0223, requires_grad=True)
w:  tensor(0.9178, requires_grad=True)
w:  tensor(0.8343, requires_grad=True)
w:  tensor(0.7674, requires_grad=True)
w:  tensor(0.7139, requires_grad=True)
w:  tensor(0.6711, requires_grad=True)
w:  tensor(0.6369, requires_grad=True)
w:  tensor(0.6095, requires_grad=True)
w:  tensor(0.5876, requires_grad=True)
w:  tensor(0.5701, requires_grad=True)
w:  tensor(0.5561, requires_grad=True)
w:  tensor(0.5449, requires_grad=True)
w:  tensor(0.5359, requires_grad=True)
w:  tensor(0.5287, requir

In [28]:
learning_rate = 0.1
x = torch.tensor(5.0, requires_grad=True)
for i in range(100):
    f = x ** 2
    f.backward()
    with torch.no_grad():
        x -= learning_rate * x.grad
    x.grad.zero_()
    print(x)

tensor(4., requires_grad=True)
tensor(3.2000, requires_grad=True)
tensor(2.5600, requires_grad=True)
tensor(2.0480, requires_grad=True)
tensor(1.6384, requires_grad=True)
tensor(1.3107, requires_grad=True)
tensor(1.0486, requires_grad=True)
tensor(0.8389, requires_grad=True)
tensor(0.6711, requires_grad=True)
tensor(0.5369, requires_grad=True)
tensor(0.4295, requires_grad=True)
tensor(0.3436, requires_grad=True)
tensor(0.2749, requires_grad=True)
tensor(0.2199, requires_grad=True)
tensor(0.1759, requires_grad=True)
tensor(0.1407, requires_grad=True)
tensor(0.1126, requires_grad=True)
tensor(0.0901, requires_grad=True)
tensor(0.0721, requires_grad=True)
tensor(0.0576, requires_grad=True)
tensor(0.0461, requires_grad=True)
tensor(0.0369, requires_grad=True)
tensor(0.0295, requires_grad=True)
tensor(0.0236, requires_grad=True)
tensor(0.0189, requires_grad=True)
tensor(0.0151, requires_grad=True)
tensor(0.0121, requires_grad=True)
tensor(0.0097, requires_grad=True)
tensor(0.0077, requires_

In [29]:
# t = torch.tensor(2.0, requires_grad=True)
# z = t.exp()  # this is an intermediate result
# z += 1  # this is an in-place operation
# z.backward()  #  RuntimeError!

In [30]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

housing = fetch_california_housing()

X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target, random_state=42
)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42
)

In [31]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
X_train = std_scaler.fit_transform(X_train)
X_valid = std_scaler.transform(X_valid)
X_test = std_scaler.transform(X_test)

X_train = torch.FloatTensor(X_train)
X_valid = torch.FloatTensor(X_valid)
X_test = torch.FloatTensor(X_test)

In [32]:
X_train.shape

torch.Size([11610, 8])

In [33]:
y_train = torch.FloatTensor(y_train).reshape(-1, 1)
y_valid = torch.FloatTensor(y_valid).reshape(-1, 1)
y_test = torch.FloatTensor(y_test).reshape(-1, 1)

In [34]:
torch.manual_seed(42)
n_features = X_train.shape[1]
w = torch.randn((n_features, 1), requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [35]:
learning_rate = 0.4
n_epochs = 20
for _ in range(n_epochs):
    y_pred = X_train @ w + b
    loss = ((y_pred - y_train) ** 2).mean()
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(f"Epoch: {_}, loss: {loss}")

Epoch: 0, loss: 16.159345626831055
Epoch: 1, loss: 4.881357192993164
Epoch: 2, loss: 2.2566046714782715
Epoch: 3, loss: 1.3315324783325195
Epoch: 4, loss: 0.9684615731239319
Epoch: 5, loss: 0.8144564628601074
Epoch: 6, loss: 0.7417906522750854
Epoch: 7, loss: 0.7021065354347229
Epoch: 8, loss: 0.6766047477722168
Epoch: 9, loss: 0.6577983498573303
Epoch: 10, loss: 0.6426120400428772
Epoch: 11, loss: 0.6297168135643005
Epoch: 12, loss: 0.6184876561164856
Epoch: 13, loss: 0.6085899472236633
Epoch: 14, loss: 0.5998146533966064
Epoch: 15, loss: 0.5920118093490601
Epoch: 16, loss: 0.5850624442100525
Epoch: 17, loss: 0.5788668990135193
Epoch: 18, loss: 0.5733392238616943
Epoch: 19, loss: 0.5684041380882263


In [36]:
from sklearn.metrics import mean_absolute_error

X_new = X_test
with torch.no_grad():
    y_pred = X_new @ w + b

mae = mean_absolute_error(y_pred, y_test)
mae

0.5433761477470398

In [37]:
import torch.nn as nn

torch.manual_seed(42)
model = nn.Linear(in_features=n_features, out_features=1)

In [38]:
model.bias

Parameter containing:
tensor([0.3117], requires_grad=True)

In [39]:
model.weight

Parameter containing:
tensor([[ 0.2703,  0.2935, -0.0828,  0.3248, -0.0775,  0.0713, -0.1721,  0.2076]],
       requires_grad=True)

In [40]:
for name, param in model.named_parameters():
    print(name, param.shape)

weight torch.Size([1, 8])
bias torch.Size([1])


In [41]:
print(model)

Linear(in_features=8, out_features=1, bias=True)


In [42]:
model(X_train[:2])

tensor([[-0.4718],
        [ 0.1131]], grad_fn=<AddmmBackward0>)

In [43]:
def my_hook(module, input, output):
    print("input:", input[0])
    print("output:", output)

hook = model.register_forward_hook(my_hook)

model(X_train[:2])  # hook fires here automatically

hook.remove()

input: tensor([[-0.1940, -1.0778, -0.9434,  0.0149,  0.0207, -0.5729,  0.9293, -1.4222],
        [ 0.7520, -1.8689,  0.4055, -0.2333,  1.8615,  0.2052, -0.9165,  1.0967]])
output: tensor([[-0.4718],
        [ 0.1131]], grad_fn=<AddmmBackward0>)


In [44]:
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()

In [45]:
def train_bgd(model, optimizer, criterion, X_train, y_train, n_epochs):
    for epoch in range(n_epochs):
        y_pred = model(X_train)
        loss = criterion(y_pred, y_train)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"Epoch: {epoch + 1}/{n_epochs + 1}, Loss: {loss}")

train_bgd(model, optimizer, mse, X_train, y_train, n_epochs)

Epoch: 1/21, Loss: 4.337859630584717
Epoch: 2/21, Loss: 0.7802937030792236
Epoch: 3/21, Loss: 0.6253871917724609
Epoch: 4/21, Loss: 0.6060434579849243
Epoch: 5/21, Loss: 0.595628023147583
Epoch: 6/21, Loss: 0.5873537063598633
Epoch: 7/21, Loss: 0.5802956223487854
Epoch: 8/21, Loss: 0.5741346478462219
Epoch: 9/21, Loss: 0.5687064528465271
Epoch: 10/21, Loss: 0.5639041662216187
Epoch: 11/21, Loss: 0.5596475005149841
Epoch: 12/21, Loss: 0.5558701753616333
Epoch: 13/21, Loss: 0.5525160431861877
Epoch: 14/21, Loss: 0.5495359301567078
Epoch: 15/21, Loss: 0.5468868613243103
Epoch: 16/21, Loss: 0.5445309281349182
Epoch: 17/21, Loss: 0.542434811592102
Epoch: 18/21, Loss: 0.540569007396698
Epoch: 19/21, Loss: 0.5389072299003601
Epoch: 20/21, Loss: 0.5374265313148499


In [46]:
X_new = X_test[:3]
with torch.no_grad():
    y_pred = model(X_new)

y_pred

tensor([[0.8061],
        [1.7116],
        [2.6973]])

In [47]:
torch.manual_seed(42)
model = nn.Sequential(
    nn.Linear(n_features, 50),
    nn.ReLU(),
    nn.Linear(50, 40),
    nn.ReLU(),
    nn.Linear(40, 1)
)

In [48]:
learning_rate = 0.1
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()
train_bgd(model, optimizer, mse, X_train, y_train, n_epochs)

Epoch: 1/21, Loss: 5.045465469360352
Epoch: 2/21, Loss: 2.0522449016571045
Epoch: 3/21, Loss: 1.0039821863174438
Epoch: 4/21, Loss: 0.8570016622543335
Epoch: 5/21, Loss: 0.7740564942359924
Epoch: 6/21, Loss: 0.7225767374038696
Epoch: 7/21, Loss: 0.6893671154975891
Epoch: 8/21, Loss: 0.6668996810913086
Epoch: 9/21, Loss: 0.6507717370986938
Epoch: 10/21, Loss: 0.6383918523788452
Epoch: 11/21, Loss: 0.6281980276107788
Epoch: 12/21, Loss: 0.6193386912345886
Epoch: 13/21, Loss: 0.6113160252571106
Epoch: 14/21, Loss: 0.6038690805435181
Epoch: 15/21, Loss: 0.596829354763031
Epoch: 16/21, Loss: 0.5901102423667908
Epoch: 17/21, Loss: 0.5836455821990967
Epoch: 18/21, Loss: 0.5774049162864685
Epoch: 19/21, Loss: 0.5713538527488708
Epoch: 20/21, Loss: 0.565443217754364


In [49]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset,
                          batch_size=32,
                          shuffle=True,
                          pin_memory=True,
                          num_workers=4,
                          persistent_workers=True
                          )

In [50]:
model = nn.Sequential(
    nn.Linear(n_features, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 1),
)
model.to(device)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.05)

In [51]:
def train(model, optimizer, criterion, train_loader, n_epochs):
    model.train()
    for epoch in range(n_epochs):
        total_loss = 0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device, non_blocking=True), y_batch.to(device, non_blocking=True)
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        mean_loss = total_loss / len(train_loader)
        print(f"Epoch: {epoch + 1}/{n_epochs}, Loss: {mean_loss:.4f}")

In [52]:
train(model, optimizer, mse, train_loader, n_epochs)

Epoch: 1/20, Loss: 0.5098
Epoch: 2/20, Loss: 0.4064
Epoch: 3/20, Loss: 0.3783
Epoch: 4/20, Loss: 0.3642
Epoch: 5/20, Loss: 0.3547
Epoch: 6/20, Loss: 0.3533
Epoch: 7/20, Loss: 0.3390
Epoch: 8/20, Loss: 0.3383
Epoch: 9/20, Loss: 0.3375
Epoch: 10/20, Loss: 0.3269
Epoch: 11/20, Loss: 0.3163
Epoch: 12/20, Loss: 0.3127
Epoch: 13/20, Loss: 0.3064
Epoch: 14/20, Loss: 0.3030
Epoch: 15/20, Loss: 0.3009
Epoch: 16/20, Loss: 0.2913
Epoch: 17/20, Loss: 0.2931
Epoch: 18/20, Loss: 0.2887
Epoch: 19/20, Loss: 0.2888
Epoch: 20/20, Loss: 0.2935


In [53]:
def evaluate(model, data_loader, metrics_fn, aggregate_fn=torch.mean):
    model.eval()
    metrics = []
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric = metrics_fn(y_pred, y_batch)
            metrics.append(metric)
        return aggregate_fn(torch.stack(metrics))

In [54]:
valid_dataset = TensorDataset(X_valid, y_valid)
valid_loader = DataLoader(valid_dataset, batch_size=32)
valid_mse = evaluate(model, valid_loader, mse)
valid_mse

tensor(0.2958, device='cuda:0')

In [55]:
def rmse(y_pred, y_train):
    return ((y_pred - y_train) ** 2).mean().sqrt()

In [56]:
evaluate(model, valid_loader, rmse)

tensor(0.5175, device='cuda:0')

In [57]:
valid_mse.sqrt()

tensor(0.5439, device='cuda:0')

In [58]:
evaluate(model, valid_loader, mse, aggregate_fn=lambda metrics: torch.sqrt(torch.mean(metrics)))

tensor(0.5439, device='cuda:0')

In [59]:
import torchmetrics

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric.update(y_pred, y_batch)
    return metric.compute()

In [60]:
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
evaluate(model, valid_loader, rmse)

tensor(0.5175, device='cuda:0')

In [61]:
class WideAndDeep(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )
        self.output_layer = nn.Linear(40 + n_features, 1)

    def forward(self, X):
        deep_output = self.deep_stack(X)
        wide_and_deep = torch.concat([X, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [62]:
#implementation with ModuleList

class WideAndDeepModuleList(nn.Module):
    def __init__(self, n_layers, n_features):
        super().__init__()
        self.relu = nn.ReLU()
        self.layers = nn.ModuleList([nn.Linear(n_features, 64)] +
                                        [nn.Linear(64, 64) for _ in range(n_layers - 1)])
        self.output_layer = nn.Linear(64 + n_features, 1)

    def forward(self, X):
        X_deep = X
        for layer in self.layers:
            X_deep = layer(X_deep)
            X_deep = self.relu(X_deep)
        wide_and_deep = torch.concat([X, X_deep], dim=1)
        return self.output_layer(wide_and_deep)

In [63]:
torch.manual_seed(42)
model = WideAndDeep(n_features).to(device)
learning_rate = 0.003

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()

train(model, optimizer, mse, train_loader, n_epochs)

Epoch: 1/20, Loss: 1.1569
Epoch: 2/20, Loss: 0.5770
Epoch: 3/20, Loss: 0.5223
Epoch: 4/20, Loss: 0.4874
Epoch: 5/20, Loss: 0.4621
Epoch: 6/20, Loss: 0.4451
Epoch: 7/20, Loss: 0.4315
Epoch: 8/20, Loss: 0.4213
Epoch: 9/20, Loss: 0.4088
Epoch: 10/20, Loss: 0.4087
Epoch: 11/20, Loss: 0.3959
Epoch: 12/20, Loss: 0.3943
Epoch: 13/20, Loss: 0.3923
Epoch: 14/20, Loss: 0.3928
Epoch: 15/20, Loss: 0.3760
Epoch: 16/20, Loss: 0.3768
Epoch: 17/20, Loss: 0.3671
Epoch: 18/20, Loss: 0.3667
Epoch: 19/20, Loss: 0.3613
Epoch: 20/20, Loss: 0.3607


In [64]:
evaluate(model, train_loader, mse)

tensor(0.3586, device='cuda:0')

In [65]:
class WideAndDeepv2(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )
        self.output_layer = nn.Linear(40 + n_features, 1)

    def forward(self, X):
        X_wide = X[:, :5]
        X_deep = X[:, 2:]
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [66]:
class WideAndDeepv3(nn.Module):
    def __init__(self, n_wide, n_deep):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_deep, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )
        self.output_layer = nn.Linear(40 + n_wide, 1)

    def forward(self, X_wide, X_deep):
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [67]:
train_data_wd = TensorDataset(X_train[:, :5], X_train[:, 2:], y_train)
train_loader_wd = DataLoader(train_data_wd, batch_size=32, shuffle=True)

model = WideAndDeepv3(n_wide=5, n_deep=6).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [68]:
for X_batch_wide, X_batch_deep, y_batch in train_loader_wd:
    X_batch_wide = X_batch_wide.to(device)
    X_batch_deep = X_batch_deep.to(device)
    y_batch = y_batch.to(device)
    y_pred = model(X_batch_wide, X_batch_deep)
    loss = mse(y_pred, y_batch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

model.eval()
total_loss = 0
with torch.no_grad():
  for X_batch_wide, X_batch_deep, y_batch in train_loader_wd:
      X_batch_wide = X_batch_wide.to(device)
      X_batch_deep = X_batch_deep.to(device)
      y_batch = y_batch.to(device)
      y_pred = model(X_batch_wide, X_batch_deep)
      total_loss += mse(y_pred, y_batch).item()
print(total_loss / len(train_loader_wd))

0.502318502580824


In [69]:
for *X_batch_inputs, y_batch in train_loader_wd:
    X_batch_inputs = [X.to(device) for X in X_batch_inputs]
    y_batch = y_batch.to(device)
    y_pred = model(*X_batch_inputs)
    loss = mse(y_pred, y_batch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(loss)

tensor(0.3952, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.5789, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.4093, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2533, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.6065, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.7336, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.5507, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.6318, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.7016, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.5537, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.4082, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.6789, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.4110, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2730, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.5396, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2655, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2672, device='cuda:0', grad_fn=

In [70]:
class WideAndDeepDataset(torch.utils.data.Dataset):
    def __init__(self, X_wide, X_deep, y):
        self.X_wide = X_wide
        self.X_deep = X_deep
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        input_dict = {"X_wide": self.X_wide[idx],
                      "X_deep": self.X_deep[idx]}
        return input_dict, self.y[idx]

In [71]:
train_data_named = WideAndDeepDataset(
    X_wide=X_train[:, :5], X_deep=X_train[:, 2:], y=y_train)
train_loader_named = DataLoader(train_data_named, batch_size=32, shuffle=True)

In [72]:
for inputs, y_batch in train_loader_named:
    inputs = {name: X.to(device) for name, X in inputs.items()}
    y_batch = y_batch.to(device)
    y_pred = model(X_wide=inputs["X_wide"], X_deep=inputs["X_deep"])

In [73]:
class WideAndDeepV4(nn.Module):
    def __init__(self, n_wide, n_deep):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_deep, 50),
            nn.ReLU(),
            nn.Linear(50, 50),
            nn.ReLU()
        )
        self.output_layer = nn.Linear(50 + n_wide, 1)
        self.aux_output_layer = nn.Linear(50, 1)


    def forward(self, X_wide, X_deep):
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        main_output = self.output_layer(wide_and_deep)
        aux_output = self.aux_output_layer(deep_output)
        return main_output, aux_output

In [74]:
def train_WDv4(model, optimizer, criterion, train_loader, n_epochs):
    model.train()
    for epoch in range(n_epochs):
        total_loss = 0
        for inputs, y_batch in train_loader:
            inputs = {name: X.to(device) for name, X in inputs.items()}
            y_batch = y_batch.to(device)
            y_pred, y_pred_aux = model(**inputs)
            main_loss = criterion(y_pred, y_batch)
            aux_loss = criterion(y_pred_aux, y_batch)
            loss = 0.8 * main_loss + 0.2 * aux_loss
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        mean_loss = total_loss / len(train_loader)
        print(f"Epoch: {epoch + 1}/{n_epochs}, Loss: {mean_loss:.4f}")

model = WideAndDeepV4(n_wide=5, n_deep=6).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
train_WDv4(model, optimizer, mse, train_loader_named, 100)

Epoch: 1/100, Loss: 2.7972
Epoch: 2/100, Loss: 1.1178
Epoch: 3/100, Loss: 0.9079
Epoch: 4/100, Loss: 0.8441
Epoch: 5/100, Loss: 0.8098
Epoch: 6/100, Loss: 0.7837
Epoch: 7/100, Loss: 0.7616
Epoch: 8/100, Loss: 0.7410
Epoch: 9/100, Loss: 0.7215
Epoch: 10/100, Loss: 0.7029
Epoch: 11/100, Loss: 0.6850
Epoch: 12/100, Loss: 0.6680
Epoch: 13/100, Loss: 0.6514
Epoch: 14/100, Loss: 0.6358
Epoch: 15/100, Loss: 0.6209
Epoch: 16/100, Loss: 0.6071
Epoch: 17/100, Loss: 0.5938
Epoch: 18/100, Loss: 0.5819
Epoch: 19/100, Loss: 0.5706
Epoch: 20/100, Loss: 0.5604
Epoch: 21/100, Loss: 0.5512
Epoch: 22/100, Loss: 0.5428
Epoch: 23/100, Loss: 0.5354
Epoch: 24/100, Loss: 0.5288
Epoch: 25/100, Loss: 0.5225
Epoch: 26/100, Loss: 0.5167
Epoch: 27/100, Loss: 0.5115
Epoch: 28/100, Loss: 0.5068
Epoch: 29/100, Loss: 0.5025
Epoch: 30/100, Loss: 0.4987
Epoch: 31/100, Loss: 0.4950
Epoch: 32/100, Loss: 0.4916
Epoch: 33/100, Loss: 0.4880
Epoch: 34/100, Loss: 0.4848
Epoch: 35/100, Loss: 0.4820
Epoch: 36/100, Loss: 0.4793
E

In [75]:
import torch
import torchvision
import torchvision.transforms.v2 as T

toTensor = T.Compose([T.ToImage(), T.ToDtype(torch.float32, scale=True)])

train_and_valid_data = torchvision.datasets.FashionMNIST(
    root="datasets", train=True, download=True, transform=toTensor)
test_data = torchvision.datasets.FashionMNIST(
    root="datasets", train=False, download=True, transform=toTensor)

torch.manual_seed(42)
train_data, valid_data = torch.utils.data.random_split(
    train_and_valid_data, [55_000, 5_000])

In [76]:
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
valid_loader = DataLoader(valid_data, batch_size=32)
test_loader = DataLoader(test_data, batch_size=32)

In [77]:
X_sample, y_sample = train_data[0]
X_sample.shape

torch.Size([1, 28, 28])

In [78]:
X_sample.dtype

torch.float32

In [79]:
train_and_valid_data.classes[y_sample]

'Ankle boot'

In [80]:
class ImageClassifier(nn.Module):
    def __init__(self, n_inputs, n_hidden1, n_hidden2, n_classes):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Flatten(),
            nn.Linear(n_inputs, n_hidden1),
            nn.ReLU(),
            nn.Linear(n_hidden1, n_hidden2),
            nn.ReLU(),
            nn.Linear(n_hidden2, n_classes),
        )

    def forward(self, X):
        return self.mlp(X)


torch.manual_seed(42)
model = ImageClassifier(n_inputs=28*28, n_hidden1=300, n_hidden2=100, n_classes=10).to(device)
xentropy = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [81]:
train(model, optimizer, xentropy, train_loader, 100)

Epoch: 1/100, Loss: 1.1357
Epoch: 2/100, Loss: 0.6023
Epoch: 3/100, Loss: 0.5139
Epoch: 4/100, Loss: 0.4735
Epoch: 5/100, Loss: 0.4502
Epoch: 6/100, Loss: 0.4308
Epoch: 7/100, Loss: 0.4148
Epoch: 8/100, Loss: 0.4018
Epoch: 9/100, Loss: 0.3879


KeyboardInterrupt: 

In [82]:
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=10).to(device)
evaluate_tm(model, valid_loader, accuracy)

tensor(0.8534, device='cuda:0')

In [83]:
model.eval()
X_new, y_new = next(iter(valid_loader))
X_new = X_new[:3].to(device)
with torch.no_grad():
    y_pred_logits = model(X_new)

y_pred = y_pred_logits.argmax(dim=1)
y_pred

tensor([7, 4, 2], device='cuda:0')

In [84]:
print([train_and_valid_data.classes[index] for index in y_pred])

['Sneaker', 'Coat', 'Pullover']


In [85]:
import torch.nn.functional as F

y_proba = F.softmax(y_pred_logits, dim=1)
y_proba.round(decimals=3)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0730, 0.0000, 0.8430, 0.0070,
         0.0760],
        [0.0000, 0.0000, 0.0370, 0.0000, 0.9600, 0.0000, 0.0030, 0.0000, 0.0000,
         0.0000],
        [0.0020, 0.0000, 0.9090, 0.0010, 0.0190, 0.0000, 0.0610, 0.0000, 0.0080,
         0.0000]], device='cuda:0')

In [86]:
y_top4_logits, y_top4_indices = torch.topk(y_pred_logits, k=4, dim=1)
y_top4_probas = F.softmax(y_top4_logits, dim=1)
y_top4_probas.round(decimals=3)

tensor([[0.8430, 0.0760, 0.0730, 0.0070],
        [0.9600, 0.0370, 0.0030, 0.0000],
        [0.9120, 0.0610, 0.0190, 0.0080]], device='cuda:0')

In [87]:
y_top4_indices

tensor([[7, 9, 5, 8],
        [4, 2, 6, 8],
        [2, 6, 4, 8]], device='cuda:0')

In [88]:
import optuna

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x_entropy = nn.CrossEntropyLoss()

toTensor = T.Compose([T.ToImage(), T.ToDtype(torch.float32, scale=True)])
train_and_valid_data = torchvision.datasets.FashionMNIST(
    root="datasets", train=True, download=True, transform=toTensor)
test_data = torchvision.datasets.FashionMNIST(
    root="datasets", train=False, download=True, transform=toTensor)
torch.manual_seed(42)
train_data, valid_data = torch.utils.data.random_split(
    train_and_valid_data, [55_000, 5_000])
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
valid_loader = DataLoader(valid_data, batch_size=32)
test_loader  = DataLoader(test_data,  batch_size=32)


def train(model, optimizer, criterion, data_loader, n_epochs):
    model.train()
    for epoch in range(n_epochs):
        total_loss = 0
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            total_loss += loss.item() * len(X_batch)

        mean_loss = total_loss / len(data_loader.dataset)
        print(f"Epoch: {epoch+1}/{n_epochs}, Loss: {mean_loss:.4f}")


def evaluate(model, data_loader, metrics_fn, aggregate_fn=torch.mean):
    model.eval()
    metrics = []
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric = metrics_fn(y_pred, y_batch)
            metrics.append(metric)
        return aggregate_fn(torch.stack(metrics))


def objective(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-1, log=True)
    n_hidden = trial.suggest_int("n_hidden", 20, 300)
    model = ImageClassifier(n_inputs=1*28*28, n_hidden1=n_hidden,
                            n_hidden2=n_hidden, n_classes=10).to(device)
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

    train(model, optimizer, x_entropy, train_loader, 25)

    accuracy = torchmetrics.Accuracy("multiclass", num_classes=10).to(device)
    validation_accuracy = evaluate(model, valid_loader, accuracy)
    return validation_accuracy.item()


sampler = optuna.samplers.TPESampler(seed=42)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=5)

print("Best params:", study.best_params)
print("Best val accuracy:", study.best_value)

[I 2026-05-29 09:02:57,745] A new study created in memory with name: no-name-4631918f-0c04-407b-998e-0b238bec5430


Epoch: 1/25, Loss: 2.2753
Epoch: 2/25, Loss: 2.2099
Epoch: 3/25, Loss: 2.1164
Epoch: 4/25, Loss: 1.9713
Epoch: 5/25, Loss: 1.7738
Epoch: 6/25, Loss: 1.5678
Epoch: 7/25, Loss: 1.3962
Epoch: 8/25, Loss: 1.2630
Epoch: 9/25, Loss: 1.1600
Epoch: 10/25, Loss: 1.0796
Epoch: 11/25, Loss: 1.0157
Epoch: 12/25, Loss: 0.9643
Epoch: 13/25, Loss: 0.9223
Epoch: 14/25, Loss: 0.8875
Epoch: 15/25, Loss: 0.8582
Epoch: 16/25, Loss: 0.8330
Epoch: 17/25, Loss: 0.8113
Epoch: 18/25, Loss: 0.7924
Epoch: 19/25, Loss: 0.7756
Epoch: 20/25, Loss: 0.7603
Epoch: 21/25, Loss: 0.7466
Epoch: 22/25, Loss: 0.7340
Epoch: 23/25, Loss: 0.7221
Epoch: 24/25, Loss: 0.7109
Epoch: 25/25, Loss: 0.7005


[I 2026-05-29 09:05:07,764] Trial 0 finished with value: 0.7420382499694824 and parameters: {'learning_rate': 0.00031489116479568613, 'n_hidden': 287}. Best is trial 0 with value: 0.7420382499694824.


Epoch: 1/25, Loss: 1.1399
Epoch: 2/25, Loss: 0.6072
Epoch: 3/25, Loss: 0.5152
Epoch: 4/25, Loss: 0.4764
Epoch: 5/25, Loss: 0.4528
Epoch: 6/25, Loss: 0.4350
Epoch: 7/25, Loss: 0.4209
Epoch: 8/25, Loss: 0.4090
Epoch: 9/25, Loss: 0.3974
Epoch: 10/25, Loss: 0.3875
Epoch: 11/25, Loss: 0.3783
Epoch: 12/25, Loss: 0.3699
Epoch: 13/25, Loss: 0.3625
Epoch: 14/25, Loss: 0.3551
Epoch: 15/25, Loss: 0.3482
Epoch: 16/25, Loss: 0.3418
Epoch: 17/25, Loss: 0.3352
Epoch: 18/25, Loss: 0.3285
Epoch: 19/25, Loss: 0.3240
Epoch: 20/25, Loss: 0.3185
Epoch: 21/25, Loss: 0.3126
Epoch: 22/25, Loss: 0.3090
Epoch: 23/25, Loss: 0.3035
Epoch: 24/25, Loss: 0.2989
Epoch: 25/25, Loss: 0.2938


[I 2026-05-29 09:07:22,133] Trial 1 finished with value: 0.8648487329483032 and parameters: {'learning_rate': 0.008471801418819975, 'n_hidden': 188}. Best is trial 1 with value: 0.8648487329483032.


Epoch: 1/25, Loss: 2.3047
Epoch: 2/25, Loss: 2.2987
Epoch: 3/25, Loss: 2.2926


[W 2026-05-29 09:07:42,812] Trial 2 failed with parameters: {'learning_rate': 4.207988669606632e-05, 'n_hidden': 63} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_10146/593238281.py", line 55, in objective
    train(model, optimizer, x_entropy, train_loader, 25)
  File "/tmp/ipykernel_10146/593238281.py", line 23, in train
    for X_batch, y_batch in data_loader:
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 764, in _next_data
    data = self._dataset

KeyboardInterrupt: 

In [89]:
study.best_params

{'learning_rate': 0.008471801418819975, 'n_hidden': 188}

In [90]:
study.best_value

0.8648487329483032

In [91]:
#Better approach to pass data loaders in function than by global scope

def objective(trial, train_loader, valid_loader):
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-1, log=True)
    n_hidden = trial.suggest_int("n_hidden", 20, 300)
    model = ImageClassifier(n_inputs=1*28*28, n_hidden1=n_hidden,
                            n_hidden2=n_hidden, n_classes=10).to(device)
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
    x_entropy = nn.CrossEntropyLoss()

    train(model, optimizer, x_entropy, train_loader, 25)

    accuracy = torchmetrics.Accuracy("multiclass", num_classes=10).to(device)
    validation_accuracy = evaluate(model, valid_loader, accuracy)
    return validation_accuracy.item()

objective_with_data = lambda trial: objective(
    trial, train_loader=train_loader, valid_loader=valid_loader)
study.optimize(objective_with_data, n_trials=5)

Epoch: 1/25, Loss: 2.3027
Epoch: 2/25, Loss: 2.2998
Epoch: 3/25, Loss: 2.2971
Epoch: 4/25, Loss: 2.2943
Epoch: 5/25, Loss: 2.2915
Epoch: 6/25, Loss: 2.2888
Epoch: 7/25, Loss: 2.2861


[W 2026-05-29 09:08:30,979] Trial 3 failed with parameters: {'learning_rate': 1.7073967431528103e-05, 'n_hidden': 263} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_10146/2389824075.py", line 17, in <lambda>
    objective_with_data = lambda trial: objective(
                                        ^^^^^^^^^^
  File "/tmp/ipykernel_10146/2389824075.py", line 11, in objective
    train(model, optimizer, x_entropy, train_loader, 25)
  File "/tmp/ipykernel_10146/593238281.py", line 23, in train
    for X_batch, y_batch in data_loader:
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^

KeyboardInterrupt: 

In [92]:
from functools import partial

objective_with_data = partial(objective, train_loader=train_loader,
                              valid_loader=valid_loader)

In [93]:
pruner = optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=0,
                                     interval_steps=1)
study = optuna.create_study(direction="maximize", sampler=sampler,
                            pruner=pruner)


[I 2026-05-29 09:08:34,355] A new study created in memory with name: no-name-a6dba994-352e-4928-a317-06b8c649ba60


In [94]:
def objective(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-1, log=True)
    n_hidden = trial.suggest_int("n_hidden", 20, 300)
    model = ImageClassifier(n_inputs=1*28*28, n_hidden1=n_hidden,
                            n_hidden2=n_hidden, n_classes=10).to(device)
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
    accuracy = torchmetrics.Accuracy("multiclass", num_classes=10).to(device)

    for epoch in range(25):
        model.train()
        total_loss = 0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            loss = x_entropy(model(X_batch), y_batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            total_loss += loss.item() * len(X_batch)
        print(f"Epoch {epoch+1}/25, Loss: {total_loss / len(train_loader.dataset):.4f}")

        model.eval()
        metrics = []
        with torch.no_grad():
            for X_batch, y_batch in valid_loader:
                X_batch, y_batch = X_batch.to(device), y_batch.to(device)
                metrics.append(accuracy(model(X_batch), y_batch))
        validation_accuracy = torch.mean(torch.stack(metrics)).item()

        trial.report(validation_accuracy, epoch)
        if trial.should_prune():
            raise optuna.TrialPruned()

    return validation_accuracy


sampler = optuna.samplers.TPESampler(seed=42)
pruner = optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=0,
                                     interval_steps=1)
study = optuna.create_study(direction="maximize", sampler=sampler, pruner=pruner)
study.optimize(objective, n_trials=5)

print("Best params:", study.best_params)
print("Best val accuracy:", study.best_value)

[I 2026-05-29 09:08:49,585] A new study created in memory with name: no-name-dbf65676-eacb-454a-a035-540a85e6b0f7


Epoch 1/25, Loss: 2.2732
Epoch 2/25, Loss: 2.2033
Epoch 3/25, Loss: 2.1021
Epoch 4/25, Loss: 1.9495
Epoch 5/25, Loss: 1.7482
Epoch 6/25, Loss: 1.5454
Epoch 7/25, Loss: 1.3785
Epoch 8/25, Loss: 1.2498
Epoch 9/25, Loss: 1.1511
Epoch 10/25, Loss: 1.0746
Epoch 11/25, Loss: 1.0141
Epoch 12/25, Loss: 0.9653
Epoch 13/25, Loss: 0.9252
Epoch 14/25, Loss: 0.8917
Epoch 15/25, Loss: 0.8632
Epoch 16/25, Loss: 0.8389
Epoch 17/25, Loss: 0.8176
Epoch 18/25, Loss: 0.7989
Epoch 19/25, Loss: 0.7823
Epoch 20/25, Loss: 0.7674
Epoch 21/25, Loss: 0.7537
Epoch 22/25, Loss: 0.7411
Epoch 23/25, Loss: 0.7295
Epoch 24/25, Loss: 0.7184
Epoch 25/25, Loss: 0.7080


[I 2026-05-29 09:11:14,013] Trial 0 finished with value: 0.7350716590881348 and parameters: {'learning_rate': 0.00031489116479568613, 'n_hidden': 287}. Best is trial 0 with value: 0.7350716590881348.


Epoch 1/25, Loss: 1.1569
Epoch 2/25, Loss: 0.6141
Epoch 3/25, Loss: 0.5219
Epoch 4/25, Loss: 0.4807
Epoch 5/25, Loss: 0.4547
Epoch 6/25, Loss: 0.4366
Epoch 7/25, Loss: 0.4216
Epoch 8/25, Loss: 0.4090
Epoch 9/25, Loss: 0.3980
Epoch 10/25, Loss: 0.3895
Epoch 11/25, Loss: 0.3798
Epoch 12/25, Loss: 0.3721
Epoch 13/25, Loss: 0.3653
Epoch 14/25, Loss: 0.3576
Epoch 15/25, Loss: 0.3509
Epoch 16/25, Loss: 0.3442
Epoch 17/25, Loss: 0.3387
Epoch 18/25, Loss: 0.3327
Epoch 19/25, Loss: 0.3272
Epoch 20/25, Loss: 0.3226
Epoch 21/25, Loss: 0.3174
Epoch 22/25, Loss: 0.3121
Epoch 23/25, Loss: 0.3062
Epoch 24/25, Loss: 0.3030
Epoch 25/25, Loss: 0.2979


[I 2026-05-29 09:13:42,915] Trial 1 finished with value: 0.8807722926139832 and parameters: {'learning_rate': 0.008471801418819975, 'n_hidden': 188}. Best is trial 1 with value: 0.8807722926139832.


Epoch 1/25, Loss: 2.2973
Epoch 2/25, Loss: 2.2917
Epoch 3/25, Loss: 2.2861
Epoch 4/25, Loss: 2.2806
Epoch 5/25, Loss: 2.2751
Epoch 6/25, Loss: 2.2697
Epoch 7/25, Loss: 2.2642
Epoch 8/25, Loss: 2.2587
Epoch 9/25, Loss: 2.2530
Epoch 10/25, Loss: 2.2471
Epoch 11/25, Loss: 2.2409
Epoch 12/25, Loss: 2.2344
Epoch 13/25, Loss: 2.2276
Epoch 14/25, Loss: 2.2204
Epoch 15/25, Loss: 2.2127
Epoch 16/25, Loss: 2.2046
Epoch 17/25, Loss: 2.1961
Epoch 18/25, Loss: 2.1870
Epoch 19/25, Loss: 2.1775
Epoch 20/25, Loss: 2.1673
Epoch 21/25, Loss: 2.1566
Epoch 22/25, Loss: 2.1452
Epoch 23/25, Loss: 2.1331
Epoch 24/25, Loss: 2.1204
Epoch 25/25, Loss: 2.1070


[I 2026-05-29 09:16:03,783] Trial 2 finished with value: 0.28682324290275574 and parameters: {'learning_rate': 4.207988669606632e-05, 'n_hidden': 63}. Best is trial 1 with value: 0.8807722926139832.


Epoch 1/25, Loss: 2.3010
Epoch 2/25, Loss: 2.2980
Epoch 3/25, Loss: 2.2950
Epoch 4/25, Loss: 2.2921
Epoch 5/25, Loss: 2.2891


[W 2026-05-29 09:16:38,335] Trial 3 failed with parameters: {'learning_rate': 1.7073967431528103e-05, 'n_hidden': 263} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_10146/1524039621.py", line 12, in objective
    for X_batch, y_batch in train_loader:
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/denys/DataspellProjects/Hands-On_ML/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 764, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/

KeyboardInterrupt: 

In [95]:
torch.save(model, "my_fashion_mnist.pt")

In [96]:
loaded_model = torch.load("my_fashion_mnist.pt", weights_only=False)

In [97]:
loaded_model.eval()
y_pred_logits = loaded_model(X_new)

In [98]:
torch.save(model.state_dict(), "my_fashion_mnist_weights.pt")

In [99]:
new_model = ImageClassifier(n_inputs=1*28*28, n_hidden1=300, n_hidden2=100, n_classes=10)
loaded_weights = torch.load("my_fashion_mnist_weights.pt", weights_only=True)
new_model.load_state_dict(loaded_weights)
new_model.eval()

ImageClassifier(
  (mlp): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=784, out_features=300, bias=True)
    (2): ReLU()
    (3): Linear(in_features=300, out_features=100, bias=True)
    (4): ReLU()
    (5): Linear(in_features=100, out_features=10, bias=True)
  )
)

In [101]:
model_data = {
    "model_state_dict": model.state_dict(),
    "model_hyperparameters": {"n_inputs": 1 * 28 * 28, "n_hidden1": 300,
                              "n_hidden2": 100, "n_classes": 10}
}
torch.save(model_data, "my_fashion_mnist_model.pt")

In [103]:
loaded_data = torch.load("my_fashion_mnist_model.pt")
new_model = ImageClassifier(**loaded_data["model_hyperparameters"])
new_model.load_state_dict(loaded_data["model_state_dict"])
new_model.eval()

ImageClassifier(
  (mlp): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=784, out_features=300, bias=True)
    (2): ReLU()
    (3): Linear(in_features=300, out_features=100, bias=True)
    (4): ReLU()
    (5): Linear(in_features=100, out_features=10, bias=True)
  )
)

In [104]:
torchscript_model = torch.jit.trace(model, X_new)

In [105]:
torchscript_model = torch.jit.script(model)

In [106]:
optimized_model = torch.jit.optimize_for_inference(torchscript_model)

In [107]:
torchscript_model.save("my_fashion_mnist_torchscript.pt")

In [108]:
loaded_torchscript_model = torch.jit.load("my_fashion_mnist_torchscript.pt")

In [109]:
compiled_model = torch.compile(model)