In [1]:
import torch
from torch.nn import grad, ReLU

In [2]:
X = torch.tensor([
    [1.0, 4.0, 7.0],
    [2.0, 3.0, 6.0]
])
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [3]:
X.shape

torch.Size([2, 3])

In [4]:
X.dtype

torch.float32

In [5]:
X[0, 1]

tensor(4.)

In [6]:
X[[0, 1]]

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [7]:
X[:, 1]

tensor([4., 3.])

In [8]:
10 * (X + 1)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [9]:
X.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [10]:
X.mean()

tensor(3.8333)

In [11]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [12]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

In [13]:
import numpy as np

X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [14]:
torch.tensor(np.array([
    [1, 4, 7],
    [2, 3, 6]
]), dtype=torch.float64)

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [15]:
torch.FloatTensor(np.array([[1., 4., 7.], [2., 3., 6]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [16]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [17]:
X.relu_()

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [18]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [19]:
M = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=torch.float32)
M = M.to(device)

In [20]:
M.device

device(type='cuda', index=0)

In [21]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device=device)

In [22]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

In [23]:
M = torch.rand((1000, 1000))
%timeit M @ M.T

3.95 ms ± 494 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
M = torch.rand((1000, 1000), device=device)
%timeit M @ M.T

373 μs ± 6.61 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [25]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
f

tensor(25., grad_fn=<PowBackward0>)

In [26]:
f.backward()
x.grad

tensor(10.)

In [27]:
t = 5
lr = 0.001
epochs = 100

x = torch.tensor(10.0)

w = torch.tensor(10.0, requires_grad=True)


for i in range(epochs):
    f = x * w
    L = (f - t) ** 2

    L.backward()

    # with torch.no_grad():
    #     w -= lr * w.grad
    w_detached = w.detach()
    w_detached -= lr * w.grad

    w.grad.zero_()

    print("w: ", w)

print(w.grad)

w:  tensor(8.1000, requires_grad=True)
w:  tensor(6.5800, requires_grad=True)
w:  tensor(5.3640, requires_grad=True)
w:  tensor(4.3912, requires_grad=True)
w:  tensor(3.6130, requires_grad=True)
w:  tensor(2.9904, requires_grad=True)
w:  tensor(2.4923, requires_grad=True)
w:  tensor(2.0938, requires_grad=True)
w:  tensor(1.7751, requires_grad=True)
w:  tensor(1.5201, requires_grad=True)
w:  tensor(1.3160, requires_grad=True)
w:  tensor(1.1528, requires_grad=True)
w:  tensor(1.0223, requires_grad=True)
w:  tensor(0.9178, requires_grad=True)
w:  tensor(0.8343, requires_grad=True)
w:  tensor(0.7674, requires_grad=True)
w:  tensor(0.7139, requires_grad=True)
w:  tensor(0.6711, requires_grad=True)
w:  tensor(0.6369, requires_grad=True)
w:  tensor(0.6095, requires_grad=True)
w:  tensor(0.5876, requires_grad=True)
w:  tensor(0.5701, requires_grad=True)
w:  tensor(0.5561, requires_grad=True)
w:  tensor(0.5449, requires_grad=True)
w:  tensor(0.5359, requires_grad=True)
w:  tensor(0.5287, requir

In [28]:
learning_rate = 0.1
x = torch.tensor(5.0, requires_grad=True)
for i in range(100):
    f = x ** 2
    f.backward()
    with torch.no_grad():
        x -= learning_rate * x.grad
    x.grad.zero_()
    print(x)

tensor(4., requires_grad=True)
tensor(3.2000, requires_grad=True)
tensor(2.5600, requires_grad=True)
tensor(2.0480, requires_grad=True)
tensor(1.6384, requires_grad=True)
tensor(1.3107, requires_grad=True)
tensor(1.0486, requires_grad=True)
tensor(0.8389, requires_grad=True)
tensor(0.6711, requires_grad=True)
tensor(0.5369, requires_grad=True)
tensor(0.4295, requires_grad=True)
tensor(0.3436, requires_grad=True)
tensor(0.2749, requires_grad=True)
tensor(0.2199, requires_grad=True)
tensor(0.1759, requires_grad=True)
tensor(0.1407, requires_grad=True)
tensor(0.1126, requires_grad=True)
tensor(0.0901, requires_grad=True)
tensor(0.0721, requires_grad=True)
tensor(0.0576, requires_grad=True)
tensor(0.0461, requires_grad=True)
tensor(0.0369, requires_grad=True)
tensor(0.0295, requires_grad=True)
tensor(0.0236, requires_grad=True)
tensor(0.0189, requires_grad=True)
tensor(0.0151, requires_grad=True)
tensor(0.0121, requires_grad=True)
tensor(0.0097, requires_grad=True)
tensor(0.0077, requires_

In [29]:
# t = torch.tensor(2.0, requires_grad=True)
# z = t.exp()  # this is an intermediate result
# z += 1  # this is an in-place operation
# z.backward()  #  RuntimeError!

In [30]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

housing = fetch_california_housing()

X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target, random_state=42
)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42
)

In [31]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
X_train = std_scaler.fit_transform(X_train)
X_valid = std_scaler.transform(X_valid)
X_test = std_scaler.transform(X_test)

X_train = torch.FloatTensor(X_train)
X_valid = torch.FloatTensor(X_valid)
X_test = torch.FloatTensor(X_test)

In [32]:
X_train.shape

torch.Size([11610, 8])

In [34]:
y_train = torch.FloatTensor(y_train).reshape(-1, 1)
y_valid = torch.FloatTensor(y_valid).reshape(-1, 1)
y_test = torch.FloatTensor(y_test).reshape(-1, 1)

In [35]:
torch.manual_seed(42)
n_features = X_train.shape[1]
w = torch.randn((n_features, 1), requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [36]:
learning_rate = 0.4
n_epochs = 20
for _ in range(n_epochs):
    y_pred = X_train @ w + b
    loss = ((y_pred - y_train) ** 2).mean()
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(f"Epoch: {_}, loss: {loss}")

Epoch: 0, loss: 16.159345626831055
Epoch: 1, loss: 4.881357192993164
Epoch: 2, loss: 2.2566046714782715
Epoch: 3, loss: 1.3315324783325195
Epoch: 4, loss: 0.9684615731239319
Epoch: 5, loss: 0.8144564628601074
Epoch: 6, loss: 0.7417906522750854
Epoch: 7, loss: 0.7021065354347229
Epoch: 8, loss: 0.6766047477722168
Epoch: 9, loss: 0.6577983498573303
Epoch: 10, loss: 0.6426120400428772
Epoch: 11, loss: 0.6297168135643005
Epoch: 12, loss: 0.6184876561164856
Epoch: 13, loss: 0.6085899472236633
Epoch: 14, loss: 0.5998146533966064
Epoch: 15, loss: 0.5920118093490601
Epoch: 16, loss: 0.5850624442100525
Epoch: 17, loss: 0.5788668990135193
Epoch: 18, loss: 0.5733392238616943
Epoch: 19, loss: 0.5684041380882263


In [37]:
from sklearn.metrics import mean_absolute_error

X_new = X_test
with torch.no_grad():
    y_pred = X_new @ w + b

mae = mean_absolute_error(y_pred, y_test)
mae

0.5433761477470398

In [38]:
import torch.nn as nn

torch.manual_seed(42)
model = nn.Linear(in_features=n_features, out_features=1)

In [39]:
model.bias

Parameter containing:
tensor([0.3117], requires_grad=True)

In [40]:
model.weight

Parameter containing:
tensor([[ 0.2703,  0.2935, -0.0828,  0.3248, -0.0775,  0.0713, -0.1721,  0.2076]],
       requires_grad=True)

In [41]:
for name, param in model.named_parameters():
    print(name, param.shape)

weight torch.Size([1, 8])
bias torch.Size([1])


In [42]:
print(model)

Linear(in_features=8, out_features=1, bias=True)


In [43]:
model(X_train[:2])

tensor([[-0.4718],
        [ 0.1131]], grad_fn=<AddmmBackward0>)

In [44]:
def my_hook(module, input, output):
    print("input:", input[0])
    print("output:", output)

hook = model.register_forward_hook(my_hook)

model(X_train[:2])  # hook fires here automatically

hook.remove()

input: tensor([[-0.1940, -1.0778, -0.9434,  0.0149,  0.0207, -0.5729,  0.9293, -1.4222],
        [ 0.7520, -1.8689,  0.4055, -0.2333,  1.8615,  0.2052, -0.9165,  1.0967]])
output: tensor([[-0.4718],
        [ 0.1131]], grad_fn=<AddmmBackward0>)


In [45]:
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()

In [46]:
def train_bgd(model, optimizer, criterion, X_train, y_train, n_epochs):
    for epoch in range(n_epochs):
        y_pred = model(X_train)
        loss = criterion(y_pred, y_train)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"Epoch: {epoch + 1}/{n_epochs + 1}, Loss: {loss}")

train_bgd(model, optimizer, mse, X_train, y_train, n_epochs)

Epoch: 1/21, Loss: 4.337859630584717
Epoch: 2/21, Loss: 0.7802937030792236
Epoch: 3/21, Loss: 0.6253871917724609
Epoch: 4/21, Loss: 0.6060434579849243
Epoch: 5/21, Loss: 0.595628023147583
Epoch: 6/21, Loss: 0.5873537063598633
Epoch: 7/21, Loss: 0.5802956223487854
Epoch: 8/21, Loss: 0.5741346478462219
Epoch: 9/21, Loss: 0.5687064528465271
Epoch: 10/21, Loss: 0.5639041662216187
Epoch: 11/21, Loss: 0.5596475005149841
Epoch: 12/21, Loss: 0.5558701753616333
Epoch: 13/21, Loss: 0.5525160431861877
Epoch: 14/21, Loss: 0.5495359301567078
Epoch: 15/21, Loss: 0.5468868613243103
Epoch: 16/21, Loss: 0.5445309281349182
Epoch: 17/21, Loss: 0.542434811592102
Epoch: 18/21, Loss: 0.540569007396698
Epoch: 19/21, Loss: 0.5389072299003601
Epoch: 20/21, Loss: 0.5374265313148499


In [47]:
X_new = X_test[:3]
with torch.no_grad():
    y_pred = model(X_new)

y_pred

tensor([[0.8061],
        [1.7116],
        [2.6973]])

In [48]:
torch.manual_seed(42)
model = nn.Sequential(
    nn.Linear(n_features, 50),
    nn.ReLU(),
    nn.Linear(50, 40),
    nn.ReLU(),
    nn.Linear(40, 1)
)

In [49]:
learning_rate = 0.1
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()
train_bgd(model, optimizer, mse, X_train, y_train, n_epochs)

Epoch: 1/21, Loss: 5.045465469360352
Epoch: 2/21, Loss: 2.0522449016571045
Epoch: 3/21, Loss: 1.0039821863174438
Epoch: 4/21, Loss: 0.8570016622543335
Epoch: 5/21, Loss: 0.7740564942359924
Epoch: 6/21, Loss: 0.7225767374038696
Epoch: 7/21, Loss: 0.6893671154975891
Epoch: 8/21, Loss: 0.6668996810913086
Epoch: 9/21, Loss: 0.6507717370986938
Epoch: 10/21, Loss: 0.6383918523788452
Epoch: 11/21, Loss: 0.6281980276107788
Epoch: 12/21, Loss: 0.6193386912345886
Epoch: 13/21, Loss: 0.6113160252571106
Epoch: 14/21, Loss: 0.6038690805435181
Epoch: 15/21, Loss: 0.596829354763031
Epoch: 16/21, Loss: 0.5901102423667908
Epoch: 17/21, Loss: 0.5836455821990967
Epoch: 18/21, Loss: 0.5774049162864685
Epoch: 19/21, Loss: 0.5713538527488708
Epoch: 20/21, Loss: 0.565443217754364


In [50]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset,
                          batch_size=32,
                          shuffle=True,
                          pin_memory=True,
                          num_workers=4,
                          persistent_workers=True
                          )

In [51]:
model = nn.Sequential(
    nn.Linear(n_features, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 1),
)
model.to(device)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.05)

In [52]:
def train(model, optimizer, criterion, train_loader, n_epochs):
    model.train()
    for epoch in range(n_epochs):
        total_loss = 0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device, non_blocking=True), y_batch.to(device, non_blocking=True)
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        mean_loss = total_loss / len(train_loader)
        print(f"Epoch: {epoch + 1}/{n_epochs}, Loss: {mean_loss:.4f}")

In [53]:
train(model, optimizer, mse, train_loader, n_epochs)

Epoch: 1/21, Loss: 0.5098
Epoch: 2/21, Loss: 0.4064
Epoch: 3/21, Loss: 0.3783
Epoch: 4/21, Loss: 0.3642
Epoch: 5/21, Loss: 0.3547
Epoch: 6/21, Loss: 0.3533
Epoch: 7/21, Loss: 0.3390
Epoch: 8/21, Loss: 0.3383
Epoch: 9/21, Loss: 0.3375
Epoch: 10/21, Loss: 0.3269
Epoch: 11/21, Loss: 0.3163
Epoch: 12/21, Loss: 0.3127
Epoch: 13/21, Loss: 0.3064
Epoch: 14/21, Loss: 0.3030
Epoch: 15/21, Loss: 0.3009
Epoch: 16/21, Loss: 0.2913
Epoch: 17/21, Loss: 0.2931
Epoch: 18/21, Loss: 0.2887
Epoch: 19/21, Loss: 0.2888
Epoch: 20/21, Loss: 0.2935


In [ ]:
def evaluate(model, data_loader, metrics_fn, aggregate_fn=torch.mean):
    model.eval()
    metrics = []
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric = metrics_fn(y_pred, y_batch)
            metrics.append(metric)
        return aggregate_fn(torch.stack(metrics))

In [55]:
valid_dataset = TensorDataset(X_valid, y_valid)
valid_loader = DataLoader(valid_dataset, batch_size=32)
valid_mse = evaluate(model, valid_loader, mse)
valid_mse

tensor(0.2958, device='cuda:0')

In [56]:
def rmse(y_pred, y_train):
    return ((y_pred - y_train) ** 2).mean().sqrt()

In [57]:
evaluate(model, valid_loader, rmse)

tensor(0.5175, device='cuda:0')

In [58]:
valid_mse.sqrt()

tensor(0.5439, device='cuda:0')

In [59]:
evaluate(model, valid_loader, mse, aggregate_fn=lambda metrics: torch.sqrt(torch.mean(metrics)))

tensor(0.5439, device='cuda:0')

In [60]:
import torchmetrics

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric.update(y_pred, y_batch)
    return metric.compute()

In [61]:
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
evaluate(model, valid_loader, rmse)

tensor(0.5175, device='cuda:0')

In [62]:
class WideAndDeep(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )
        self.output_layer = nn.Linear(40 + n_features, 1)

    def forward(self, X):
        deep_output = self.deep_stack(X)
        wide_and_deep = torch.concat([X, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [63]:
#implementation with ModuleList

class WideAndDeepModuleList(nn.Module):
    def __init__(self, n_layers, n_features):
        super().__init__()
        self.relu = nn.ReLU()
        self.layers = nn.ModuleList([nn.Linear(n_features, 64)] +
                                        [nn.Linear(64, 64) for _ in range(n_layers - 1)])
        self.output_layer = nn.Linear(64 + n_features, 1)

    def forward(self, X):
        X_deep = X
        for layer in self.layers:
            X_deep = layer(X_deep)
            X_deep = self.relu(X_deep)
        wide_and_deep = torch.concat([X, X_deep], dim=1)
        return self.output_layer(wide_and_deep)

In [66]:
torch.manual_seed(42)
model = WideAndDeep(n_features).to(device)
learning_rate = 0.003

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()

train(model, optimizer, mse, train_loader, n_epochs)

Epoch: 1/21, Loss: 1.1569
Epoch: 2/21, Loss: 0.5770
Epoch: 3/21, Loss: 0.5223
Epoch: 4/21, Loss: 0.4874
Epoch: 5/21, Loss: 0.4621
Epoch: 6/21, Loss: 0.4451
Epoch: 7/21, Loss: 0.4315
Epoch: 8/21, Loss: 0.4213
Epoch: 9/21, Loss: 0.4088
Epoch: 10/21, Loss: 0.4087
Epoch: 11/21, Loss: 0.3959
Epoch: 12/21, Loss: 0.3943
Epoch: 13/21, Loss: 0.3923
Epoch: 14/21, Loss: 0.3928
Epoch: 15/21, Loss: 0.3760
Epoch: 16/21, Loss: 0.3768
Epoch: 17/21, Loss: 0.3671
Epoch: 18/21, Loss: 0.3667
Epoch: 19/21, Loss: 0.3613
Epoch: 20/21, Loss: 0.3607


In [69]:
evaluate(model, train_loader, mse)

tensor(0.3588, device='cuda:0')

In [70]:
class WideAndDeepv2(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )
        self.output_layer = nn.Linear(40 + n_features, 1)

    def forward(self, X):
        X_wide = X[:, :5]
        X_deep = X[:, 2:]
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [84]:
class WideAndDeepv3(nn.Module):
    def __init__(self, n_wide, n_deep):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_deep, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )
        self.output_layer = nn.Linear(40 + n_wide, 1)

    def forward(self, X_wide, X_deep):
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [86]:
train_data_wd = TensorDataset(X_train[:, :5], X_train[:, 2:], y_train)
train_loader_wd = DataLoader(train_data_wd, batch_size=32, shuffle=True)

model = WideAndDeepv3(n_wide=5, n_deep=6).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [89]:
for X_batch_wide, X_batch_deep, y_batch in train_loader_wd:
    X_batch_wide = X_batch_wide.to(device)
    X_batch_deep = X_batch_deep.to(device)
    y_batch = y_batch.to(device)
    y_pred = model(X_batch_wide, X_batch_deep)
    loss = mse(y_pred, y_batch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

model.eval()
total_loss = 0
with torch.no_grad():
  for X_batch_wide, X_batch_deep, y_batch in train_loader_wd:
      X_batch_wide = X_batch_wide.to(device)
      X_batch_deep = X_batch_deep.to(device)
      y_batch = y_batch.to(device)
      y_pred = model(X_batch_wide, X_batch_deep)
      total_loss += mse(y_pred, y_batch).item()
print(total_loss / len(train_loader_wd))

0.45180862257385385


In [96]:
for *X_batch_inputs, y_batch in train_loader_wd:
    X_batch_inputs = [X.to(device) for X in X_batch_inputs]
    y_batch = y_batch.to(device)
    y_pred = model(*X_batch_inputs)
    loss = mse(y_pred, y_batch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(loss)

tensor(0.1431, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.3938, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.5688, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.3338, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.1531, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2274, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.4773, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.7590, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.6667, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.4687, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.4712, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2457, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.4180, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.3560, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2737, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.2270, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(0.5322, device='cuda:0', grad_fn=

In [97]:
class WideAndDeepDataset(torch.utils.data.Dataset):
    def __init__(self, X_wide, X_deep, y):
        self.X_wide = X_wide
        self.X_deep = X_deep
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        input_dict = {"X_wide": self.X_wide[idx],
                      "X_deep": self.X_deep[idx]}
        return input_dict, self.y[idx]

In [99]:
train_data_named = WideAndDeepDataset(
    X_wide=X_train[:, :5], X_deep=X_train[:, 2:], y=y_train)
train_loader_named = DataLoader(train_data_named, batch_size=32, shuffle=True)

In [102]:
for inputs, y_batch in train_loader_named:
    inputs = {name: X.to(device) for name, X in inputs.items()}
    y_batch = y_batch.to(device)
    y_pred = model(X_wide=inputs["X_wide"], X_deep=inputs["X_deep"])